import type { DiagonalizationShareState } from '../sharing';

export interface DiagonalizationTeachingScenario {
  readonly id: string;
  readonly title: string;
  readonly observation: string;
  readonly answer: string;
  readonly state: DiagonalizationShareState;
  /** ソルバーから生成せず、行列構造・手計算で独立に固定する。行列は行配列。 */
  readonly expected: {
    readonly roots: readonly { readonly value: number; readonly multiplicity: number; readonly dimension: number }[];
    readonly image: readonly number[];
    readonly p?: readonly (readonly number[])[];
    readonly d?: readonly (readonly number[])[];
    readonly c?: readonly number[];
    readonly dc?: readonly number[];
  };
}

/** 第13〜14週の資料専用。アプリからimportせず、公開URLと回帰検証の正本にする。 */
export const DIAGONALIZATION_TEACHING_SCENARIOS: readonly DiagonalizationTeachingScenario[] = [
  {"id":"initial","title":"基準座標と固有基底座標","observation":"左右の図は異なるベクトルを示しているのか。","answer":"同じ入力と像の別座標表示。Pは右の座標を左の基準座標へ戻す。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[4,1],[0,2]],"input":[1,2],"order":[0,1],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":2,"multiplicity":1,"dimension":1},{"value":4,"multiplicity":1,"dimension":1}],"image":[6,4],"p":[[-0.5,1],[1,0]],"d":[[2,0],[0,4]],"c":[2,2],"dc":[4,8]}},
  {"id":"reordered","title":"基底の列順だけを交換","observation":"前例から基底の1番目と2番目を交換し、何が変わらないかを確かめる。","answer":"PとDの対応順は変わるが入力と像は不変。この入力ではcの両成分は同じだが、Dcの順序は変わる。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[4,1],[0,2]],"input":[1,2],"order":[1,0],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":2,"multiplicity":1,"dimension":1},{"value":4,"multiplicity":1,"dimension":1}],"image":[6,4],"p":[[1,-0.5],[0,1]],"d":[[4,0],[0,2]],"c":[2,2],"dc":[8,4]}},
  {"id":"symmetric","title":"斜めの固有ベクトル基底","observation":"固有値1の方向で入力と像が重なる場合も、数値で確認する。","answer":"基底(1,−1)、(1,1)で対角成分は1、3。座標ごとの倍率として読める。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[2,1],[1,2]],"input":[3,1],"order":[0,1],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":1,"multiplicity":1,"dimension":1},{"value":3,"multiplicity":1,"dimension":1}],"image":[7,5],"p":[[1,1],[-1,1]],"d":[[1,0],[0,3]],"c":[1,2],"dc":[1,6]}},
  {"id":"scalar","title":"重根でも対角化できる","observation":"次の例と、重複度だけでなく固有空間の次元を比較する。","answer":"固有値2の重複度2、固有空間の次元2。基底は一意ではない。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[2,0],[0,2]],"input":[1,2],"order":[0,1],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":2,"multiplicity":2,"dimension":2}],"image":[2,4],"p":[[1,0],[0,1]],"d":[[2,0],[0,2]],"c":[1,2],"dc":[2,4]}},
  {"id":"jordan","title":"同じ重根でも基底が足りない","observation":"前例と固有値が同じなのに、なぜ右の座標を構成できないか。","answer":"固有値2の重複度2に対して固有空間の次元1。完全な実固有ベクトル基底を作れない。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[2,1],[0,2]],"input":[1,2],"order":null,"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":2,"multiplicity":2,"dimension":1}],"image":[4,4]}},
  {"id":"rotation","title":"実数上で対角化できない回転","observation":"実固有値がない場合と数値判定保留を区別する。","answer":"90度回転は実固有値を持たず、実数上の対角化は不可。複素数の対角化は扱わない。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[0,-1],[1,0]],"input":[1,2],"order":null,"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[],"image":[-2,1]}},
  {"id":"repeated-3d","title":"3Dの重根と固有平面","observation":"固有値2の平面から何本選べるか。","answer":"固有値−1の直線から1本、固有値2の平面から2本選べる。自動基底は(e3,e1,e2)の順。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":3,"matrix":[[2,0,0],[0,2,0],[0,0,-1]],"input":[1,2,3],"order":[0,1,2],"showEigenspace":false,"cameras":{"reference":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1},"eigenbasis":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}}},"expected":{"roots":[{"value":-1,"multiplicity":1,"dimension":1},{"value":2,"multiplicity":2,"dimension":2}],"image":[2,4,-3],"p":[[0,1,0],[0,0,1],[1,0,0]],"d":[[-1,0,0],[0,2,0],[0,0,2]],"c":[3,1,2],"dc":[-3,2,4]}},
  {"id":"zero-map","title":"正の次元の零変換","observation":"像が零でも対角化できるか。","answer":"固有値0の固有空間は2次元全体。標準基底を選べてDは零行列。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[0,0],[0,0]],"input":[1,2],"order":[0,1],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":0,"multiplicity":2,"dimension":2}],"image":[0,0],"p":[[1,0],[0,1]],"d":[[0,0],[0,0]],"c":[1,2],"dc":[0,0]}},
  {"id":"zero-input","title":"零入力でも行列の判定は不変","observation":"入力を零に変えると対角化の可否は変わるか。","answer":"行列の固有値2、4と対角化可能性は不変。零入力を固有ベクトルとは呼ばない。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":2,"matrix":[[4,1],[0,2]],"input":[0,0],"order":[0,1],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":2,"multiplicity":1,"dimension":1},{"value":4,"multiplicity":1,"dimension":1}],"image":[0,0],"p":[[-0.5,1],[1,0]],"d":[[2,0],[0,4]],"c":[0,0],"dc":[0,0]}},
  {"id":"zero-space","title":"0Dの空基底","observation":"正の次元の零変換と比較する。","answer":"固有値・非零固有ベクトルはない。空基底と0×0行列で形式的に対角化できる。","state":{"v":1,"lab":"diagonalization","dim":0},"expected":{"roots":[],"image":[],"p":[],"d":[],"c":[],"dc":[]}},
  {"id":"negative-1d","title":"1Dの反転","observation":"負の対角成分を数直線で読む。","answer":"P=[1]、D=[−2]。1次元の自己写像は初めから対角行列。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":1,"matrix":[[-2]],"input":[1],"order":[0],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":-2,"multiplicity":1,"dimension":1}],"image":[-2],"p":[[1]],"d":[[-2]],"c":[1],"dc":[-2]}},
  {"id":"zero-1d","title":"1Dの零変換","observation":"0Dと違い、基底が1本必要であることを確認する。","answer":"固有値0、固有空間の次元1。非零の基底を選べる。","state":{"v":1,"lab":"diagonalization","kind":"coordinate","dim":1,"matrix":[[0]],"input":[2],"order":[0],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":0,"multiplicity":1,"dimension":1}],"image":[0],"p":[[1]],"d":[[0]],"c":[2],"dc":[0]}},
  {"id":"polynomial-constant","title":"定数多項式の微分","observation":"定数多項式空間は0Dか1Dか。","answer":"T(f(x))=f′(x)はここでは零変換。基底(1)でD=[0]、対角化可能。","state":{"v":1,"lab":"diagonalization","kind":"polynomial","dim":1,"matrix":[[0]],"input":[2],"order":[0],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":0,"multiplicity":1,"dimension":1}],"image":[0],"p":[[1]],"d":[[0]],"c":[2],"dc":[0]}},
  {"id":"polynomial-linear","title":"高々1次の次数作用","observation":"1とxの像をそれぞれ求める。","answer":"T(f(x))=xf′(x)。基底(1,x)で対角成分0、1。入力1+2xの像は2x。","state":{"v":1,"lab":"diagonalization","kind":"polynomial","dim":2,"matrix":[[0,0],[0,1]],"input":[1,2],"order":[0,1],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":0,"multiplicity":1,"dimension":1},{"value":1,"multiplicity":1,"dimension":1}],"image":[0,2],"p":[[1,0],[0,1]],"d":[[0,0],[0,1]],"c":[1,2],"dc":[0,2]}},
  {"id":"polynomial-degree","title":"高々2次の次数作用","observation":"関数グラフではなく、基底に関する係数空間であることを説明する。","answer":"T(f(x))=xf′(x)。基底(1,x,x²)で対角成分0、1、2。入力1+2x+3x²の像は2x+6x²。","state":{"v":1,"lab":"diagonalization","kind":"polynomial","dim":3,"matrix":[[0,0,0],[0,1,0],[0,0,2]],"input":[1,2,3],"order":[0,1,2],"showEigenspace":false,"cameras":{"reference":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1},"eigenbasis":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}}},"expected":{"roots":[{"value":0,"multiplicity":1,"dimension":1},{"value":1,"multiplicity":1,"dimension":1},{"value":2,"multiplicity":1,"dimension":1}],"image":[0,2,6],"p":[[1,0,0],[0,1,0],[0,0,1]],"d":[[0,0,0],[0,1,0],[0,0,2]],"c":[1,2,3],"dc":[0,2,6]}},
  {"id":"polynomial-derivative","title":"高々2次の微分","observation":"定数多項式だけの例との違いは何か。","answer":"T(f(x))=f′(x)。固有値0の重複度3、固有空間の次元1で対角化不可。像は2+6x。","state":{"v":1,"lab":"diagonalization","kind":"polynomial","dim":3,"matrix":[[0,1,0],[0,0,2],[0,0,0]],"input":[1,2,3],"order":null,"showEigenspace":false,"cameras":{"reference":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1},"eigenbasis":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}}},"expected":{"roots":[{"value":0,"multiplicity":3,"dimension":1}],"image":[2,6,0]}},
  {"id":"polynomial-translation","title":"高々2次の平行移動","observation":"重複度3というだけで対角化できると言えるか。","answer":"T(f(x))=f(x+1)。固有値1の重複度3、固有空間の次元1で対角化不可。像は6+8x+3x²。","state":{"v":1,"lab":"diagonalization","kind":"polynomial","dim":3,"matrix":[[1,1,1],[0,1,2],[0,0,1]],"input":[1,2,3],"order":null,"showEigenspace":false,"cameras":{"reference":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1},"eigenbasis":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}}},"expected":{"roots":[{"value":1,"multiplicity":3,"dimension":1}],"image":[6,8,3]}},
  {"id":"polynomial-oblique","title":"単項式とは異なる固有基底","observation":"入力2+3xを基底(1,1+x)の一次結合で表す。","answer":"T(1)=0、T(x)=1+xで定義される線形変換。2+3x=−1·1+3(1+x)。像は3+3xであり、固有基底では座標ごとに0倍・1倍する。","state":{"v":1,"lab":"diagonalization","kind":"polynomial","dim":2,"matrix":[[0,1],[0,1]],"input":[2,3],"order":[0,1],"showEigenspace":false,"cameras":{"reference":null,"eigenbasis":null}},"expected":{"roots":[{"value":0,"multiplicity":1,"dimension":1},{"value":1,"multiplicity":1,"dimension":1}],"image":[3,3],"p":[[1,1],[0,1]],"d":[[0,0],[0,1]],"c":[-1,3],"dc":[0,3]}},
];
