import type { EigenspaceShareState } from '../sharing';

export interface EigenTeachingScenario {
  readonly id: string;
  readonly title: string;
  readonly observation: string;
  readonly answer: string;
  readonly state: EigenspaceShareState;
  /** 解析結果から生成せず、行列構造・手計算で独立に固定した期待値。 */
  readonly expected: {
    readonly coefficients: readonly number[];
    readonly roots: readonly { readonly value: number; readonly multiplicity: number; readonly basis: readonly (readonly number[])[] }[];
    readonly image: readonly number[];
    readonly inputStatus: 'eigenvector' | 'not-eigenvector' | 'zero-input';
  };
}

/** 第12週の教員用資料。アプリからimportせず、URLと検証の正本だけに使う。 */
export const EIGEN_TEACHING_SCENARIOS: readonly EigenTeachingScenario[] = [
  {"id":"discover","title":"最初の探索","observation":"固有空間を表示せず入力を動かし、像が定数倍になる方向を探す。","answer":"固有値2・4。固有直線はy=−2xとx軸。最初の入力は固有ベクトルではない。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[4,1],[0,2]],"input":[1,2],"showEigenspace":false,"camera":null},"expected":{"coefficients":[8,-6,1],"roots":[{"value":2,"multiplicity":1,"basis":[[-1,2]]},{"value":4,"multiplicity":1,"basis":[[1,0]]}],"image":[6,4],"inputStatus":"not-eigenvector"}},
  {"id":"line-negative","title":"1Dの反転","observation":"入力を正負に動かす。零入力との違いは何か。","answer":"固有値−2。非零入力すべてが固有ベクトルで、像は逆向き・長さ2倍。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":1,"matrix":[[-2]],"input":[1],"showEigenspace":false,"camera":null},"expected":{"coefficients":[-2,-1],"roots":[{"value":-2,"multiplicity":1,"basis":[[1]]}],"image":[-2],"inputStatus":"eigenvector"}},
  {"id":"plane-sign","title":"2Dの伸縮と反転","observation":"各座標軸の方向に入力を置き、像の向きと長さを比較する。","answer":"x軸では2倍、y軸では−1倍。一般の入力には共通の固有倍率を割り当てられない。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[2,0],[0,-1]],"input":[1,1],"showEigenspace":false,"camera":null},"expected":{"coefficients":[-2,-1,1],"roots":[{"value":-1,"multiplicity":1,"basis":[[0,1]]},{"value":2,"multiplicity":1,"basis":[[1,0]]}],"image":[2,-1],"inputStatus":"not-eigenvector"}},
  {"id":"oblique","title":"斜めの固有直線と倍率1","observation":"y=xとy=−xで比較する。入力と像が一致するとき何が見えるか。","answer":"固有値3では長さ3倍。固有値1の方向では入力と像が一致するが、両ラベルを確認できる。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[2,1],[1,2]],"input":[1,1],"showEigenspace":false,"camera":null},"expected":{"coefficients":[3,-4,1],"roots":[{"value":1,"multiplicity":1,"basis":[[1,-1]]},{"value":3,"multiplicity":1,"basis":[[1,1]]}],"image":[3,3],"inputStatus":"eigenvector"}},
  {"id":"zero-eigenvalue","title":"固有値0","observation":"入力は非零、像は零。この入力は固有ベクトルか。","answer":"固有値0の固有空間はy軸（行列の核）。非零入力が零へ写っても固有ベクトルである。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[2,0],[0,0]],"input":[0,1],"showEigenspace":false,"camera":null},"expected":{"coefficients":[0,-2,1],"roots":[{"value":0,"multiplicity":1,"basis":[[0,1]]},{"value":2,"multiplicity":1,"basis":[[1,0]]}],"image":[0,0],"inputStatus":"eigenvector"}},
  {"id":"scalar","title":"重複度2・固有空間次元2","observation":"どの非零入力を選んでも2倍になるか。次の例と比較する。","answer":"固有値2の重複度は2、固有空間は平面全体で次元2。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[2,0],[0,2]],"input":[1,2],"showEigenspace":false,"camera":null},"expected":{"coefficients":[4,-4,1],"roots":[{"value":2,"multiplicity":2,"basis":[[1,0],[0,1]]}],"image":[2,4],"inputStatus":"eigenvector"}},
  {"id":"jordan","title":"同じ重複度でも直線のみ","observation":"前例と固有方程式が同じでも、固有空間の次元は同じか。","answer":"固有値2の重複度は2だが、固有空間はx軸で次元1。対角化の話題には進まない。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[2,1],[0,2]],"input":[0,1],"showEigenspace":false,"camera":null},"expected":{"coefficients":[4,-4,1],"roots":[{"value":2,"multiplicity":2,"basis":[[1,0]]}],"image":[1,2],"inputStatus":"not-eigenvector"}},
  {"id":"rotation","title":"実固有値なし","observation":"どの非零入力も回転する。固有方程式に実数解はあるか。","answer":"固有多項式はλ²+1。実固有値・実固有空間なし。数値判定保留とは異なる。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[0,-1],[1,0]],"input":[1,0],"showEigenspace":false,"camera":null},"expected":{"coefficients":[1,0,1],"roots":[],"image":[0,1],"inputStatus":"not-eigenvector"}},
  {"id":"space-plane","title":"3Dの平面と直線","observation":"固有空間を表示して視点を変える。平面内とz軸上の入力を比較する。","answer":"固有値2の固有空間はxy平面、−1の固有空間はz軸。両者を一つの全空間として描かない。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":3,"matrix":[[2,0,0],[0,2,0],[0,0,-1]],"input":[1,1,0],"showEigenspace":false,"camera":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}},"expected":{"coefficients":[-4,0,3,-1],"roots":[{"value":-1,"multiplicity":1,"basis":[[0,0,1]]},{"value":2,"multiplicity":2,"basis":[[1,0,0],[0,1,0]]}],"image":[2,2,0],"inputStatus":"eigenvector"}},
  {"id":"space-one","title":"3Dでも実固有値は1個","observation":"xy平面の回転とz方向の伸縮を比較する。","answer":"実固有値は2のみ、固有空間はz軸。残る2根は実数ではなく、この授業の固有値に含めない。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":3,"matrix":[[0,-1,0],[1,0,0],[0,0,2]],"input":[0,0,1],"showEigenspace":false,"camera":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}},"expected":{"coefficients":[2,-1,2,-1],"roots":[{"value":2,"multiplicity":1,"basis":[[0,0,1]]}],"image":[0,0,2],"inputStatus":"eigenvector"}},
  {"id":"zero-map","title":"正の次元の零変換","observation":"固有空間と固有ベクトルの違いを説明する。","answer":"固有値0・固有空間は平面全体。零入力だけは固有ベクトルではない。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[0,0],[0,0]],"input":[1,2],"showEigenspace":false,"camera":null},"expected":{"coefficients":[0,0,1],"roots":[{"value":0,"multiplicity":2,"basis":[[1,0],[0,1]]}],"image":[0,0],"inputStatus":"eigenvector"}},
  {"id":"zero-input","title":"零入力から固有値は特定できない","observation":"零入力が等式を満たしても、なぜ固有ベクトルと呼ばないか。","answer":"任意の実数λで零の等式が成立。入力には非零条件が必要。行列の固有値自体は2・4のまま。","state":{"v":1,"lab":"eigenspace","kind":"coordinate","dim":2,"matrix":[[4,1],[0,2]],"input":[0,0],"showEigenspace":false,"camera":null},"expected":{"coefficients":[8,-6,1],"roots":[{"value":2,"multiplicity":1,"basis":[[-1,2]]},{"value":4,"multiplicity":1,"basis":[[1,0]]}],"image":[0,0],"inputStatus":"zero-input"}},
  {"id":"zero-space","title":"0Dと零変換の違い","observation":"正の次元の零変換と比較する。","answer":"非零ベクトルが存在しないので固有値・固有ベクトルなし。固有多項式は1。","state":{"v":1,"lab":"eigenspace","dim":0},"expected":{"coefficients":[1],"roots":[],"image":[],"inputStatus":"zero-input"}},
  {"id":"polynomial-constant","title":"定数多項式の微分","observation":"定数多項式の空間は0次元なのか。","answer":"定数多項式空間は1次元。微分は零変換で固有値0を持つ。","state":{"v":1,"lab":"eigenspace","kind":"polynomial","dim":1,"matrix":[[0]],"input":[2],"showEigenspace":false,"camera":null},"expected":{"coefficients":[0,-1],"roots":[{"value":0,"multiplicity":1,"basis":[[1]]}],"image":[0],"inputStatus":"eigenvector"}},
  {"id":"polynomial-linear","title":"高々1次の次数作用","observation":"定数とxの係数を別々に変える。","answer":"xf′の固有値は0・1。入力1+2xの像は2x。","state":{"v":1,"lab":"eigenspace","kind":"polynomial","dim":2,"matrix":[[0,0],[0,1]],"input":[1,2],"showEigenspace":false,"camera":null},"expected":{"coefficients":[0,-1,1],"roots":[{"value":0,"multiplicity":1,"basis":[[1,0]]},{"value":1,"multiplicity":1,"basis":[[0,1]]}],"image":[0,2],"inputStatus":"not-eigenvector"}},
  {"id":"polynomial-derivative","title":"高々2次の微分","observation":"重複度3でも固有空間の次元が1なのはなぜか。","answer":"入力1+2x+3x²の像は2+6x。固有値0の重複度3、固有空間は定数多項式の直線。","state":{"v":1,"lab":"eigenspace","kind":"polynomial","dim":3,"matrix":[[0,1,0],[0,0,2],[0,0,0]],"input":[1,2,3],"showEigenspace":false,"camera":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}},"expected":{"coefficients":[0,0,0,-1],"roots":[{"value":0,"multiplicity":3,"basis":[[1,0,0]]}],"image":[2,6,0],"inputStatus":"not-eigenvector"}},
  {"id":"polynomial-degree","title":"高々2次の次数作用","observation":"1・x・x²がそれぞれどう写るか。","answer":"xf′の固有値は0・1・2。入力の像は2x+6x²。固有空間は各単項式の倍数。","state":{"v":1,"lab":"eigenspace","kind":"polynomial","dim":3,"matrix":[[0,0,0],[0,1,0],[0,0,2]],"input":[1,2,3],"showEigenspace":false,"camera":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}},"expected":{"coefficients":[0,-2,3,-1],"roots":[{"value":0,"multiplicity":1,"basis":[[1,0,0]]},{"value":1,"multiplicity":1,"basis":[[0,1,0]]},{"value":2,"multiplicity":1,"basis":[[0,0,1]]}],"image":[0,2,6],"inputStatus":"not-eigenvector"}},
  {"id":"polynomial-translation","title":"高々2次の平行移動","observation":"係数空間の矢印と関数グラフの平行移動を混同しないよう説明する。","answer":"f(x+1)の固有値は1（重複度3）、固有空間は定数多項式の直線。像は6+8x+3x²。","state":{"v":1,"lab":"eigenspace","kind":"polynomial","dim":3,"matrix":[[1,1,1],[0,1,2],[0,0,1]],"input":[1,2,3],"showEigenspace":false,"camera":{"direction":[0.50305546,-0.68060445,0.53264696],"target":[0,0,0],"up":[0,0,1],"zoom":1}},"expected":{"coefficients":[1,-3,3,-1],"roots":[{"value":1,"multiplicity":3,"basis":[[1,0,0]]}],"image":[6,8,3],"inputStatus":"not-eigenvector"}},
];
